-- Migration v4: order tracking. Placing an order doesn't touch current
-- stock — it just records incoming quantity until someone marks it
-- delivered (which adds it to stock) or cancels it (which discards it).
-- Multiple concurrent orders per asset are allowed.
-- Run this in the Supabase SQL Editor (safe to run more than once).

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    asset_id bigint references public.assets on delete cascade not null,
    quantity integer not null check (quantity > 0),
    reason text,
    created_by uuid references auth.users not null,
    created_at timestamptz default now()
);

alter table public.orders enable row level security;

drop policy if exists "Authenticated users can read orders" on public.orders;
create policy "Authenticated users can read orders"
    on public.orders for select
    to authenticated
    using (true);

drop policy if exists "Authenticated users can insert orders" on public.orders;
create policy "Authenticated users can insert orders"
    on public.orders for insert
    to authenticated
    with check (auth.uid() = created_by);

drop policy if exists "Authenticated users can delete orders" on public.orders;
create policy "Authenticated users can delete orders"
    on public.orders for delete
    to authenticated
    using (true);

-- Allow ORDER, DELIVER and CANCEL entries in the history audit trail
alter table public.history drop constraint if exists history_action_check;
alter table public.history
    add constraint history_action_check
    check (action in ('ADD', 'REMOVE', 'EDIT', 'DELETE', 'ORDER', 'DELIVER', 'CANCEL'));
