-- Migration v5: multi-location support (multiple offices sharing one site,
-- each with its own isolated inventory) plus an admin role.
-- Run this in the Supabase SQL Editor (safe to run more than once).

-- 1. Locations (offices) -----------------------------------------------

create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz default now()
);

-- 2. Which users belong to which locations (many-to-many: a user, e.g. a
--    regional manager, can belong to more than one office) -------------

create table if not exists public.user_locations (
    user_id uuid references auth.users on delete cascade not null,
    location_id bigint references public.locations on delete cascade not null,
    created_at timestamptz default now(),
    primary key (user_id, location_id)
);

-- 3. Role + email on profiles (email is denormalized from auth.users so
--    the admin panel can list users without needing service-role access) --

alter table public.profiles add column if not exists role text not null default 'member';
-- "add column if not exists" is a no-op when role already exists (e.g. from an earlier
-- experiment), so its old default/constraint/nullability survive unless forced here too
alter table public.profiles drop constraint if exists profiles_role_check;
update public.profiles set role = 'member' where role is null or role not in ('admin', 'member');
alter table public.profiles alter column role set default 'member';
alter table public.profiles alter column role set not null;
alter table public.profiles add constraint profiles_role_check check (role in ('admin', 'member'));

alter table public.profiles add column if not exists email text;
update public.profiles p set email = u.email from auth.users u where p.id = u.id and p.email is null;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name, email)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
        new.email
    );
    return new;
end;
$$;

-- 4. Tag existing tables with a location ---------------------------------

alter table public.assets add column if not exists location_id bigint references public.locations;
alter table public.history add column if not exists location_id bigint references public.locations;
alter table public.orders add column if not exists location_id bigint references public.locations;

-- 5. Backfill: everything that exists today belongs to Nashville Office,
--    and every current user gets access to it so nobody loses access ----

insert into public.locations (name) values ('Nashville Office')
    on conflict (name) do nothing;

do $$
declare
    v_location_id bigint;
begin
    select id into v_location_id from public.locations where name = 'Nashville Office';

    update public.assets set location_id = v_location_id where location_id is null;
    update public.history set location_id = v_location_id where location_id is null;
    update public.orders set location_id = v_location_id where location_id is null;

    insert into public.user_locations (user_id, location_id)
    select id, v_location_id from auth.users
    on conflict (user_id, location_id) do nothing;
end $$;

alter table public.assets alter column location_id set not null;
alter table public.orders alter column location_id set not null;

-- 6. Bootstrap the first admin -------------------------------------------

update public.profiles
set role = 'admin'
where id = (select id from auth.users where email = 'spyakurel@isuitellc.com');

-- 7. Helper functions (security definer so RLS policies below don't
--    recurse into the tables they're protecting) ------------------------

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select exists (
        select 1 from public.profiles where id = auth.uid() and role = 'admin'
    );
$$;

create or replace function public.has_location_access(loc_id bigint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select public.is_admin() or exists (
        select 1 from public.user_locations
        where user_id = auth.uid() and location_id = loc_id
    );
$$;

-- 8. RLS: locations ------------------------------------------------------

alter table public.locations enable row level security;

drop policy if exists "Authenticated users can read locations" on public.locations;
create policy "Authenticated users can read locations"
    on public.locations for select
    to authenticated
    using (true);

drop policy if exists "Admins can insert locations" on public.locations;
create policy "Admins can insert locations"
    on public.locations for insert
    to authenticated
    with check (public.is_admin());

drop policy if exists "Admins can update locations" on public.locations;
create policy "Admins can update locations"
    on public.locations for update
    to authenticated
    using (public.is_admin());

-- 9. RLS: user_locations ---------------------------------------------------

alter table public.user_locations enable row level security;

drop policy if exists "Users can read own memberships, admins read all" on public.user_locations;
create policy "Users can read own memberships, admins read all"
    on public.user_locations for select
    to authenticated
    using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can insert memberships" on public.user_locations;
create policy "Admins can insert memberships"
    on public.user_locations for insert
    to authenticated
    with check (public.is_admin());

drop policy if exists "Admins can delete memberships" on public.user_locations;
create policy "Admins can delete memberships"
    on public.user_locations for delete
    to authenticated
    using (public.is_admin());

-- 10. RLS: assets, history, orders — scoped to the caller's location(s) --

drop policy if exists "Authenticated users can read assets" on public.assets;
create policy "Users can read assets in their locations"
    on public.assets for select
    to authenticated
    using (public.has_location_access(location_id));

drop policy if exists "Authenticated users can insert assets" on public.assets;
create policy "Users can insert assets in their locations"
    on public.assets for insert
    to authenticated
    with check (auth.uid() = created_by and public.has_location_access(location_id));

drop policy if exists "Authenticated users can update assets" on public.assets;
create policy "Users can update assets in their locations"
    on public.assets for update
    to authenticated
    using (public.has_location_access(location_id));

drop policy if exists "Authenticated users can delete assets" on public.assets;
create policy "Users can delete assets in their locations"
    on public.assets for delete
    to authenticated
    using (public.has_location_access(location_id));

drop policy if exists "Authenticated users can read history" on public.history;
create policy "Users can read history in their locations"
    on public.history for select
    to authenticated
    using (location_id is null or public.has_location_access(location_id));

drop policy if exists "Authenticated users can insert history" on public.history;
create policy "Users can insert history in their locations"
    on public.history for insert
    to authenticated
    with check (auth.uid() = user_id and (location_id is null or public.has_location_access(location_id)));

drop policy if exists "Authenticated users can read orders" on public.orders;
create policy "Users can read orders in their locations"
    on public.orders for select
    to authenticated
    using (public.has_location_access(location_id));

drop policy if exists "Authenticated users can insert orders" on public.orders;
create policy "Users can insert orders in their locations"
    on public.orders for insert
    to authenticated
    with check (auth.uid() = created_by and public.has_location_access(location_id));

drop policy if exists "Authenticated users can delete orders" on public.orders;
create policy "Users can delete orders in their locations"
    on public.orders for delete
    to authenticated
    using (public.has_location_access(location_id));
