-- Run this in the Supabase SQL Editor before deploying.

create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    full_name text,
    created_at timestamptz default now()
);

create table if not exists public.assets (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    quantity integer not null default 0 check (quantity >= 0),
    reorder_level integer not null default 5 check (reorder_level >= 0),
    description text,
    created_by uuid references auth.users not null,
    created_at timestamptz default now()
);

create table if not exists public.history (
    id bigint generated by default as identity primary key,
    asset_id bigint references public.assets on delete set null,
    user_id uuid references auth.users not null,
    action text not null check (action in ('ADD', 'REMOVE', 'EDIT', 'DELETE')),
    quantity integer not null check (quantity > 0),
    reason text,
    done_by text,
    created_at timestamptz default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
    );
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.assets enable row level security;
alter table public.history enable row level security;

create policy "Authenticated users can read profiles"
    on public.profiles for select
    to authenticated
    using (true);

create policy "Authenticated users can read assets"
    on public.assets for select
    to authenticated
    using (true);

create policy "Authenticated users can insert assets"
    on public.assets for insert
    to authenticated
    with check (auth.uid() = created_by);

create policy "Authenticated users can update assets"
    on public.assets for update
    to authenticated
    using (true);

create policy "Authenticated users can delete assets"
    on public.assets for delete
    to authenticated
    using (true);

create policy "Authenticated users can read history"
    on public.history for select
    to authenticated
    using (true);

create policy "Authenticated users can insert history"
    on public.history for insert
    to authenticated
    with check (auth.uid() = user_id);
